"""initial_v1_schema

Revision ID: 6c0d16adcbc7
Revises: 
Create Date: 2026-09-17 23:31:36.806356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0d16adcbc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_tmdb_id'), 'genres', ['tmdb_id'], unique=True)
    op.create_table('industries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_tmdb_id'), 'people', ['tmdb_id'], unique=True)
    op.create_table('titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_date_precision', sa.String(length=20), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('tmdb_rating', sa.Float(), nullable=True),
    sa.Column('tmdb_vote_count', sa.Integer(), nullable=True),
    sa.Column('tmdb_popularity', sa.Float(), nullable=True),
    sa.Column('is_anime', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('movie', 'tv')", name='check_title_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_is_anime'), 'titles', ['is_anime'], unique=False)
    op.create_index(op.f('ix_titles_original_language'), 'titles', ['original_language'], unique=False)
    op.create_index('ix_titles_rating_vote_count', 'titles', ['tmdb_rating', 'tmdb_vote_count'], unique=False)
    op.create_index(op.f('ix_titles_release_date'), 'titles', ['release_date'], unique=False)
    op.create_index(op.f('ix_titles_tmdb_id'), 'titles', ['tmdb_id'], unique=True)
    op.create_index('ix_titles_tmdb_popularity', 'titles', ['tmdb_popularity'], unique=False)
    op.create_index(op.f('ix_titles_type'), 'titles', ['type'], unique=False)
    op.create_table('watch_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_providers_tmdb_provider_id'), 'watch_providers', ['tmdb_provider_id'], unique=True)
    op.create_table('alternate_titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternate_titles_title'), 'alternate_titles', ['title'], unique=False)
    op.create_index(op.f('ix_alternate_titles_title_id'), 'alternate_titles', ['title_id'], unique=False)
    op.create_table('credits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('credit_type', sa.String(length=50), nullable=False),
    sa.Column('character', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_person_id'), 'credits', ['person_id'], unique=False)
    op.create_index('ix_credits_title_credit_type', 'credits', ['title_id', 'credit_type'], unique=False)
    op.create_index(op.f('ix_credits_title_id'), 'credits', ['title_id'], unique=False)
    op.create_table('external_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=50), nullable=True),
    sa.Column('wikidata_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_ids_imdb_id'), 'external_ids', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_external_ids_title_id'), 'external_ids', ['title_id'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_season_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id', 'season_number', name='uq_seasons_title_season_number')
    )
    op.create_index(op.f('ix_seasons_title_id'), 'seasons', ['title_id'], unique=False)
    op.create_index(op.f('ix_seasons_tmdb_season_id'), 'seasons', ['tmdb_season_id'], unique=True)
    op.create_table('title_countries',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'country_id')
    )
    op.create_table('title_genres',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'genre_id')
    )
    op.create_table('title_industries',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_industry_confidence_range'),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'industry_id')
    )
    op.create_table('title_languages',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'language_id')
    )
    op.create_table('title_watch_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('offer_type', sa.String(length=50), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['watch_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id', 'provider_id', 'country_code', 'offer_type', name='uq_title_watch_provider_offer')
    )
    op.create_index(op.f('ix_title_watch_providers_provider_id'), 'title_watch_providers', ['provider_id'], unique=False)
    op.create_index('ix_title_watch_providers_title_country', 'title_watch_providers', ['title_id', 'country_code'], unique=False)
    op.create_index(op.f('ix_title_watch_providers_title_id'), 'title_watch_providers', ['title_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_title_watch_providers_title_id'), table_name='title_watch_providers')
    op.drop_index('ix_title_watch_providers_title_country', table_name='title_watch_providers')
    op.drop_index(op.f('ix_title_watch_providers_provider_id'), table_name='title_watch_providers')
    op.drop_table('title_watch_providers')
    op.drop_table('title_languages')
    op.drop_table('title_industries')
    op.drop_table('title_genres')
    op.drop_table('title_countries')
    op.drop_index(op.f('ix_seasons_tmdb_season_id'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_title_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_external_ids_title_id'), table_name='external_ids')
    op.drop_index(op.f('ix_external_ids_imdb_id'), table_name='external_ids')
    op.drop_table('external_ids')
    op.drop_index(op.f('ix_credits_title_id'), table_name='credits')
    op.drop_index('ix_credits_title_credit_type', table_name='credits')
    op.drop_index(op.f('ix_credits_person_id'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_alternate_titles_title_id'), table_name='alternate_titles')
    op.drop_index(op.f('ix_alternate_titles_title'), table_name='alternate_titles')
    op.drop_table('alternate_titles')
    op.drop_index(op.f('ix_watch_providers_tmdb_provider_id'), table_name='watch_providers')
    op.drop_table('watch_providers')
    op.drop_index(op.f('ix_titles_type'), table_name='titles')
    op.drop_index('ix_titles_tmdb_popularity', table_name='titles')
    op.drop_index(op.f('ix_titles_tmdb_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_release_date'), table_name='titles')
    op.drop_index('ix_titles_rating_vote_count', table_name='titles')
    op.drop_index(op.f('ix_titles_original_language'), table_name='titles')
    op.drop_index(op.f('ix_titles_is_anime'), table_name='titles')
    op.drop_table('titles')
    op.drop_index(op.f('ix_people_tmdb_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_table('industries')
    op.drop_index(op.f('ix_genres_tmdb_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
