"""composite_unique_tmdb_id_type

Revision ID: d98bb1cdd79c
Revises: 6c0d16adcbc7
Create Date: 2026-09-17 23:38:43.843374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98bb1cdd79c'
down_revision: Union[str, Sequence[str], None] = '6c0d16adcbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_titles_tmdb_id'), table_name='titles')
    op.create_index(op.f('ix_titles_tmdb_id'), 'titles', ['tmdb_id'], unique=False)
    op.create_unique_constraint('uq_titles_tmdb_id_type', 'titles', ['tmdb_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_titles_tmdb_id_type', 'titles', type_='unique')
    op.drop_index(op.f('ix_titles_tmdb_id'), table_name='titles')
    op.create_index(op.f('ix_titles_tmdb_id'), 'titles', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###
